/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rb3oVBMiuW2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "./ui/avatar"
import { Button } from "./ui/button"
import { Input } from "./ui/input"

export function ChatBot() {
  return (
    (<div
      className="flex flex-col h-[600px] w-[400px] bg-background rounded-lg shadow-lg overflow-hidden">
      <div
        className="bg-primary text-primary-foreground py-3 px-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <div>
            <h3 className="font-semibold">Gemini AI Chatbot</h3>
            <p className="text-sm text-primary-foreground/80">Powered by Google</p>
          </div>
        </div>
        <Button variant="ghost" size="icon">
          <XIcon className="w-5 h-5" />
          <span className="sr-only">Close</span>
        </Button>
      </div>
      <div className="flex-1 overflow-auto p-4 space-y-4">
        <div
          className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
          <p>Hello! I'm Gemini, an AI assistant powered by Google. How can I help you today?</p>
        </div>
        <div
          className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
          <p>Hi Gemini! I'm looking for information on the latest advancements in renewable energy technology.</p>
        </div>
        <div
          className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
          <p>
            Great, let me provide you with some information on the latest advancements in renewable energy technology:
          </p>
          <ul className="list-disc pl-4 space-y-2">
            <li>
              Solar panels are becoming more efficient and affordable, with new materials and manufacturing processes.
            </li>
            <li>
              Wind turbines are getting larger and more powerful, with improved blade designs and tower structures.
            </li>
            <li>
              Battery storage technology is advancing rapidly, allowing for better integration of renewable energy into
              the grid.
            </li>
            <li>
              Geothermal energy is becoming more accessible, with new drilling techniques and heat pump technologies.
            </li>
          </ul>
          <p>Let me know if you have any other questions!</p>
        </div>
      </div>
      <div className="bg-muted px-4 py-3 flex items-center gap-2">
        <Input
          id="message"
          placeholder="Type your message..."
          className="flex-1"
          autoComplete="off" />
        <Button type="submit" size="icon">
          <SendIcon className="w-4 h-4" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>)
  );
}

function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
